#include "Arduino.h"
#include "test.h"

extern LEUARTClass Serial;

void test05(uint8_t){Serial.println("\n\rRun test05");}
void test06(uint8_t){Serial.println("\n\rRun test06");}
void test07(uint8_t){Serial.println("\n\rRun test07");}
void test08(uint8_t){Serial.println("\n\rRun test08");}
void test09(uint8_t){Serial.println("\n\rRun test09");}
void test10(uint8_t){Serial.println("\n\rRun test10");}
void test11(uint8_t){Serial.println("\n\rRun test11");}
void test12(uint8_t){Serial.println("\n\rRun test12");}
void test13(uint8_t){Serial.println("\n\rRun test13");}
void test14(uint8_t){Serial.println("\n\rRun test14");}
void test15(uint8_t){Serial.println("\n\rRun test15");}
void test16(uint8_t){Serial.println("\n\rRun test16");}
void test17(uint8_t){Serial.println("\n\rRun test17");}
void test18(uint8_t){Serial.println("\n\rRun test18");}
void test19(uint8_t){Serial.println("\n\rRun test19");}
void test20(uint8_t){Serial.println("\n\rRun test20");}
void test21(uint8_t){Serial.println("\n\rRun test21");}
void test22(uint8_t){Serial.println("\n\rRun test22");}
void test23(uint8_t){Serial.println("\n\rRun test23");}
void test24(uint8_t){Serial.println("\n\rRun test24");}
void test25(uint8_t){Serial.println("\n\rRun test25");}
void test26(uint8_t){Serial.println("\n\rRun test26");}
void test27(uint8_t){Serial.println("\n\rRun test27");}
void test28(uint8_t){Serial.println("\n\rRun test28");}
void test29(uint8_t){Serial.println("\n\rRun test29");}
void test30(uint8_t){Serial.println("\n\rRun test30");}
void test31(uint8_t){Serial.println("\n\rRun test31");}
void test32(uint8_t){Serial.println("\n\rRun test32");}
void test33(uint8_t){Serial.println("\n\rRun test33");}
void test34(uint8_t){Serial.println("\n\rRun test34");}
void test35(uint8_t){Serial.println("\n\rRun test35");}
void test36(uint8_t){Serial.println("\n\rRun test36");}
void test37(uint8_t){Serial.println("\n\rRun test37");}
void test38(uint8_t){Serial.println("\n\rRun test38");}
void test39(uint8_t){Serial.println("\n\rRun test39");}
void test40(uint8_t){Serial.println("\n\rRun test40");}
void test41(uint8_t){Serial.println("\n\rRun test41");}
void test42(uint8_t){Serial.println("\n\rRun test42");}
void test43(uint8_t){Serial.println("\n\rRun test43");}
void test44(uint8_t){Serial.println("\n\rRun test44");}
void test45(uint8_t){Serial.println("\n\rRun test45");}
void test46(uint8_t){Serial.println("\n\rRun test46");}
void test47(uint8_t){Serial.println("\n\rRun test47");}
void test48(uint8_t){Serial.println("\n\rRun test48");}
void test49(uint8_t){Serial.println("\n\rRun test49");}
